package com.beetech.serialport.greendao.dao;

import android.database.Cursor;
import android.database.sqlite.SQLiteStatement;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.Property;
import org.greenrobot.greendao.internal.DaoConfig;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.database.DatabaseStatement;

import com.beetech.serialport.code.response.ReadDataResponse;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.
/** 
 * DAO for table "READ_DATA_RESPONSE".
*/
public class ReadDataResponseDao extends AbstractDao<ReadDataResponse, Long> {

    public static final String TABLENAME = "READ_DATA_RESPONSE";

    /**
     * Properties of entity ReadDataResponse.<br/>
     * Can be used for QueryBuilder and for referencing column names.
     */
    public static class Properties {
        public final static Property _id = new Property(0, Long.class, "_id", true, "_id");
        public final static Property SensorId = new Property(1, String.class, "sensorId", false, "SENSOR_ID");
        public final static Property SensorDataTime = new Property(2, java.util.Date.class, "sensorDataTime", false, "SENSOR_DATA_TIME");
        public final static Property Temp = new Property(3, double.class, "temp", false, "TEMP");
        public final static Property Temp1 = new Property(4, double.class, "temp1", false, "TEMP1");
        public final static Property Temp2 = new Property(5, double.class, "temp2", false, "TEMP2");
        public final static Property Temp3 = new Property(6, double.class, "temp3", false, "TEMP3");
        public final static Property Temp4 = new Property(7, double.class, "temp4", false, "TEMP4");
        public final static Property Temp5 = new Property(8, double.class, "temp5", false, "TEMP5");
        public final static Property Temp6 = new Property(9, double.class, "temp6", false, "TEMP6");
        public final static Property Temp7 = new Property(10, double.class, "temp7", false, "TEMP7");
        public final static Property Rh = new Property(11, double.class, "rh", false, "RH");
        public final static Property Rh1 = new Property(12, double.class, "rh1", false, "RH1");
        public final static Property Rh2 = new Property(13, double.class, "rh2", false, "RH2");
        public final static Property Rh3 = new Property(14, double.class, "rh3", false, "RH3");
        public final static Property Rh4 = new Property(15, double.class, "rh4", false, "RH4");
        public final static Property Rh5 = new Property(16, double.class, "rh5", false, "RH5");
        public final static Property Rh6 = new Property(17, double.class, "rh6", false, "RH6");
        public final static Property Rh7 = new Property(18, double.class, "rh7", false, "RH7");
        public final static Property InputTime = new Property(19, java.util.Date.class, "inputTime", false, "INPUT_TIME");
        public final static Property SendFlag = new Property(20, int.class, "sendFlag", false, "SEND_FLAG");
        public final static Property Cid = new Property(21, int.class, "cid", false, "CID");
        public final static Property Csq = new Property(22, int.class, "csq", false, "CSQ");
        public final static Property Lac = new Property(23, int.class, "lac", false, "LAC");
        public final static Property Mcc = new Property(24, int.class, "mcc", false, "MCC");
        public final static Property Mnc = new Property(25, int.class, "mnc", false, "MNC");
        public final static Property Power = new Property(26, int.class, "power", false, "POWER");
        public final static Property Battery = new Property(27, int.class, "battery", false, "BATTERY");
    }


    public ReadDataResponseDao(DaoConfig config) {
        super(config);
    }
    
    public ReadDataResponseDao(DaoConfig config, DaoSession daoSession) {
        super(config, daoSession);
    }

    /** Creates the underlying database table. */
    public static void createTable(Database db, boolean ifNotExists) {
        String constraint = ifNotExists? "IF NOT EXISTS ": "";
        db.execSQL("CREATE TABLE " + constraint + "\"READ_DATA_RESPONSE\" (" + //
                "\"_id\" INTEGER PRIMARY KEY AUTOINCREMENT ," + // 0: _id
                "\"SENSOR_ID\" TEXT," + // 1: sensorId
                "\"SENSOR_DATA_TIME\" INTEGER," + // 2: sensorDataTime
                "\"TEMP\" REAL NOT NULL ," + // 3: temp
                "\"TEMP1\" REAL NOT NULL ," + // 4: temp1
                "\"TEMP2\" REAL NOT NULL ," + // 5: temp2
                "\"TEMP3\" REAL NOT NULL ," + // 6: temp3
                "\"TEMP4\" REAL NOT NULL ," + // 7: temp4
                "\"TEMP5\" REAL NOT NULL ," + // 8: temp5
                "\"TEMP6\" REAL NOT NULL ," + // 9: temp6
                "\"TEMP7\" REAL NOT NULL ," + // 10: temp7
                "\"RH\" REAL NOT NULL ," + // 11: rh
                "\"RH1\" REAL NOT NULL ," + // 12: rh1
                "\"RH2\" REAL NOT NULL ," + // 13: rh2
                "\"RH3\" REAL NOT NULL ," + // 14: rh3
                "\"RH4\" REAL NOT NULL ," + // 15: rh4
                "\"RH5\" REAL NOT NULL ," + // 16: rh5
                "\"RH6\" REAL NOT NULL ," + // 17: rh6
                "\"RH7\" REAL NOT NULL ," + // 18: rh7
                "\"INPUT_TIME\" INTEGER," + // 19: inputTime
                "\"SEND_FLAG\" INTEGER NOT NULL ," + // 20: sendFlag
                "\"CID\" INTEGER NOT NULL ," + // 21: cid
                "\"CSQ\" INTEGER NOT NULL ," + // 22: csq
                "\"LAC\" INTEGER NOT NULL ," + // 23: lac
                "\"MCC\" INTEGER NOT NULL ," + // 24: mcc
                "\"MNC\" INTEGER NOT NULL ," + // 25: mnc
                "\"POWER\" INTEGER NOT NULL ," + // 26: power
                "\"BATTERY\" INTEGER NOT NULL );"); // 27: battery
    }

    /** Drops the underlying database table. */
    public static void dropTable(Database db, boolean ifExists) {
        String sql = "DROP TABLE " + (ifExists ? "IF EXISTS " : "") + "\"READ_DATA_RESPONSE\"";
        db.execSQL(sql);
    }

    @Override
    protected final void bindValues(DatabaseStatement stmt, ReadDataResponse entity) {
        stmt.clearBindings();
 
        Long _id = entity.get_id();
        if (_id != null) {
            stmt.bindLong(1, _id);
        }
 
        String sensorId = entity.getSensorId();
        if (sensorId != null) {
            stmt.bindString(2, sensorId);
        }
 
        java.util.Date sensorDataTime = entity.getSensorDataTime();
        if (sensorDataTime != null) {
            stmt.bindLong(3, sensorDataTime.getTime());
        }
        stmt.bindDouble(4, entity.getTemp());
        stmt.bindDouble(5, entity.getTemp1());
        stmt.bindDouble(6, entity.getTemp2());
        stmt.bindDouble(7, entity.getTemp3());
        stmt.bindDouble(8, entity.getTemp4());
        stmt.bindDouble(9, entity.getTemp5());
        stmt.bindDouble(10, entity.getTemp6());
        stmt.bindDouble(11, entity.getTemp7());
        stmt.bindDouble(12, entity.getRh());
        stmt.bindDouble(13, entity.getRh1());
        stmt.bindDouble(14, entity.getRh2());
        stmt.bindDouble(15, entity.getRh3());
        stmt.bindDouble(16, entity.getRh4());
        stmt.bindDouble(17, entity.getRh5());
        stmt.bindDouble(18, entity.getRh6());
        stmt.bindDouble(19, entity.getRh7());
 
        java.util.Date inputTime = entity.getInputTime();
        if (inputTime != null) {
            stmt.bindLong(20, inputTime.getTime());
        }
        stmt.bindLong(21, entity.getSendFlag());
        stmt.bindLong(22, entity.getCid());
        stmt.bindLong(23, entity.getCsq());
        stmt.bindLong(24, entity.getLac());
        stmt.bindLong(25, entity.getMcc());
        stmt.bindLong(26, entity.getMnc());
        stmt.bindLong(27, entity.getPower());
        stmt.bindLong(28, entity.getBattery());
    }

    @Override
    protected final void bindValues(SQLiteStatement stmt, ReadDataResponse entity) {
        stmt.clearBindings();
 
        Long _id = entity.get_id();
        if (_id != null) {
            stmt.bindLong(1, _id);
        }
 
        String sensorId = entity.getSensorId();
        if (sensorId != null) {
            stmt.bindString(2, sensorId);
        }
 
        java.util.Date sensorDataTime = entity.getSensorDataTime();
        if (sensorDataTime != null) {
            stmt.bindLong(3, sensorDataTime.getTime());
        }
        stmt.bindDouble(4, entity.getTemp());
        stmt.bindDouble(5, entity.getTemp1());
        stmt.bindDouble(6, entity.getTemp2());
        stmt.bindDouble(7, entity.getTemp3());
        stmt.bindDouble(8, entity.getTemp4());
        stmt.bindDouble(9, entity.getTemp5());
        stmt.bindDouble(10, entity.getTemp6());
        stmt.bindDouble(11, entity.getTemp7());
        stmt.bindDouble(12, entity.getRh());
        stmt.bindDouble(13, entity.getRh1());
        stmt.bindDouble(14, entity.getRh2());
        stmt.bindDouble(15, entity.getRh3());
        stmt.bindDouble(16, entity.getRh4());
        stmt.bindDouble(17, entity.getRh5());
        stmt.bindDouble(18, entity.getRh6());
        stmt.bindDouble(19, entity.getRh7());
 
        java.util.Date inputTime = entity.getInputTime();
        if (inputTime != null) {
            stmt.bindLong(20, inputTime.getTime());
        }
        stmt.bindLong(21, entity.getSendFlag());
        stmt.bindLong(22, entity.getCid());
        stmt.bindLong(23, entity.getCsq());
        stmt.bindLong(24, entity.getLac());
        stmt.bindLong(25, entity.getMcc());
        stmt.bindLong(26, entity.getMnc());
        stmt.bindLong(27, entity.getPower());
        stmt.bindLong(28, entity.getBattery());
    }

    @Override
    public Long readKey(Cursor cursor, int offset) {
        return cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0);
    }    

    @Override
    public ReadDataResponse readEntity(Cursor cursor, int offset) {
        ReadDataResponse entity = new ReadDataResponse( //
            cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0), // _id
            cursor.isNull(offset + 1) ? null : cursor.getString(offset + 1), // sensorId
            cursor.isNull(offset + 2) ? null : new java.util.Date(cursor.getLong(offset + 2)), // sensorDataTime
            cursor.getDouble(offset + 3), // temp
            cursor.getDouble(offset + 4), // temp1
            cursor.getDouble(offset + 5), // temp2
            cursor.getDouble(offset + 6), // temp3
            cursor.getDouble(offset + 7), // temp4
            cursor.getDouble(offset + 8), // temp5
            cursor.getDouble(offset + 9), // temp6
            cursor.getDouble(offset + 10), // temp7
            cursor.getDouble(offset + 11), // rh
            cursor.getDouble(offset + 12), // rh1
            cursor.getDouble(offset + 13), // rh2
            cursor.getDouble(offset + 14), // rh3
            cursor.getDouble(offset + 15), // rh4
            cursor.getDouble(offset + 16), // rh5
            cursor.getDouble(offset + 17), // rh6
            cursor.getDouble(offset + 18), // rh7
            cursor.isNull(offset + 19) ? null : new java.util.Date(cursor.getLong(offset + 19)), // inputTime
            cursor.getInt(offset + 20), // sendFlag
            cursor.getInt(offset + 21), // cid
            cursor.getInt(offset + 22), // csq
            cursor.getInt(offset + 23), // lac
            cursor.getInt(offset + 24), // mcc
            cursor.getInt(offset + 25), // mnc
            cursor.getInt(offset + 26), // power
            cursor.getInt(offset + 27) // battery
        );
        return entity;
    }
     
    @Override
    public void readEntity(Cursor cursor, ReadDataResponse entity, int offset) {
        entity.set_id(cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0));
        entity.setSensorId(cursor.isNull(offset + 1) ? null : cursor.getString(offset + 1));
        entity.setSensorDataTime(cursor.isNull(offset + 2) ? null : new java.util.Date(cursor.getLong(offset + 2)));
        entity.setTemp(cursor.getDouble(offset + 3));
        entity.setTemp1(cursor.getDouble(offset + 4));
        entity.setTemp2(cursor.getDouble(offset + 5));
        entity.setTemp3(cursor.getDouble(offset + 6));
        entity.setTemp4(cursor.getDouble(offset + 7));
        entity.setTemp5(cursor.getDouble(offset + 8));
        entity.setTemp6(cursor.getDouble(offset + 9));
        entity.setTemp7(cursor.getDouble(offset + 10));
        entity.setRh(cursor.getDouble(offset + 11));
        entity.setRh1(cursor.getDouble(offset + 12));
        entity.setRh2(cursor.getDouble(offset + 13));
        entity.setRh3(cursor.getDouble(offset + 14));
        entity.setRh4(cursor.getDouble(offset + 15));
        entity.setRh5(cursor.getDouble(offset + 16));
        entity.setRh6(cursor.getDouble(offset + 17));
        entity.setRh7(cursor.getDouble(offset + 18));
        entity.setInputTime(cursor.isNull(offset + 19) ? null : new java.util.Date(cursor.getLong(offset + 19)));
        entity.setSendFlag(cursor.getInt(offset + 20));
        entity.setCid(cursor.getInt(offset + 21));
        entity.setCsq(cursor.getInt(offset + 22));
        entity.setLac(cursor.getInt(offset + 23));
        entity.setMcc(cursor.getInt(offset + 24));
        entity.setMnc(cursor.getInt(offset + 25));
        entity.setPower(cursor.getInt(offset + 26));
        entity.setBattery(cursor.getInt(offset + 27));
     }
    
    @Override
    protected final Long updateKeyAfterInsert(ReadDataResponse entity, long rowId) {
        entity.set_id(rowId);
        return rowId;
    }
    
    @Override
    public Long getKey(ReadDataResponse entity) {
        if(entity != null) {
            return entity.get_id();
        } else {
            return null;
        }
    }

    @Override
    public boolean hasKey(ReadDataResponse entity) {
        return entity.get_id() != null;
    }

    @Override
    protected final boolean isEntityUpdateable() {
        return true;
    }
    
}
